version: 2.1

orbs:
  newspack: newspack/newspack@1.4.4

commands:
  checkout_code:
    steps:
      - checkout
      - attach_workspace:
          at: ~/

jobs:
  build:
    docker:
      - image: cimg/node:16.11.1
    steps:
      - checkout_code
      - run:
          name: Install dependencies
          command: npm start
      - persist_to_workspace:
          root: ~/
          paths:
            - project

workflows:
  version: 2
  all:
    jobs:
      - build
      - newspack/release:
          requires:
            - build
          filters:
            branches:
              only:
                - release
                - alpha
                - /^hotfix\/.*/
      - newspack/post-release:
          requires:
            - newspack/release
          filters:
            branches:
              only:
                - release
  php:
    jobs:
      - newspack/lint-php
      - newspack/test-php
